### ISSUE TITLE
Assess Mentors

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#115]
Assess volunteers who signed up as mentors to determine if they should be a mentor or a Hatchling Level 7 (like a mentor but without the responsibility) for their first project.

Ensure both volunteer spreadsheets are up to date.

**Comment by abbeyjackson** [comment]
@northtwilight @renatomcamilio I know you've given me an update already but can you capture that update on this ticket so I don't forget and have to ask you again later? ;) Thanks!

**Comment by REWMassimo** [comment]
Oh you're terrible

of course!

;)

**Comment by REWMassimo** [comment]
So we assessed all those volunteers originally listed on the intake form as having a) said they're willing & capable of handling mentor duties and b) had been processed in some form already into CDG (Slack,   participation in CDG activities, etc); the latter were listed in blue.

Copied those to a separate sheet (mentor responses) and rated each. 

Several were listed as needing reassessment as hatchlings due to inexperience. 

To expand the potential pool I also considered volunteers who hadn't yet been approached (shown in white) last night.

**Comment by abbeyjackson** [comment]
For the reassessment info, where did you indicate that? on the intake
response sheet or the volunteer reports sheet? And in it's own column or is
this a colour coded thing? (also when you and Peter finalize the colour vs
column stuff can you update the ticket here too? Thanks!)

**Comment by northtwilight** [comment]
Intake document, mentor response sheet, Founder notes - column I.

No changes to colour scheme; therefore:
blue - mentor applicants already processed
white - not processed by CDG yet, but if/when, can be assessed according to the note.

**Comment by abbeyjackson** [comment]
@northtwilight can this be closed?

**Comment by REWMassimo** [comment]
Yea
