### ISSUE TITLE
Look into Android Go

### ISSUE THREAD

**Issue by abbeyjackson** [CodeDoesGood/business#153]
Android Go is a new OS that will run on very low-spec Android devices. Some of our apps will be helpful for developing countries and to assist people in lower income brackets.

Please look into Android Go and write a summary of it's potential uses at CodeDoesGood and any special information that project facilitators, designers and developers would need to know if wanting to implement an app for this OS.

**Comment by vitalii-tym** [comment]
I will take a look.

**Comment by abbeyjackson** [comment]
@vitalii-tym  fantastic, thank you!

**Comment by vitalii-tym** [comment]
It looks like "Android Go" will be a specifically configured and tuned version of the upcoming Android O operating system. It is not clear yet whether Android O will turn itself in that "GO" mode automatically after detecting that device has <=1GB RAM or it will be a separate distributive installed on such devices by manufacturers (and we shouldn't really care about it). 

The official blog says: "The Android Go experience will ship in 2018 for all Android devices that have 1GB or less of memory." (https://android-developers.googleblog.com/2017/05/whats-new-in-android-o-developer.html).

When in "Android Go" mode the Play Store will have a special section highlighting apps, which are designed to play well with that kind of devices.

In order to be eligible for the "Android Go" section in Play Store an app has to meet a list of requirements. However, these requirements doesn't seem to be clear enough yet. Google's blog points to "Building for billions" guidelines (https://developer.android.com/develop/quality-guidelines/building-for-billions.html). The guidelines don't have concrete digits in terms of memory, data consumption, app footprint and others. It just says "try as low as possible, optimise and localise" and gives suggestions on how to do it. I expect "Android Go" requirements to be more specific because they gonna need some measurable metrics to decide whether an app can be placed in that section or not.

I'll dig deeper a little later. Will try to get some insight about what these requirements might be.

**Comment by abbeyjackson** [comment]
@vitalii-tym Thanks for all this great info! I guess we have some time (2018) to get it sorted
